GP2-3726-Dart-Sass-update
uktrade/great-styles pull request #169
Opened 2021-11-01 18:08 UTC by seijihg

update to dart-sass related to great-cms.

- [x] CSS have been compiled.

2021-11-02 08:41 UTC, froddd requested changes
A couple of changes required for readability. 

More importantly: running storybook (`npm run storybook`) highlights a few more places where the `math.div` construct needs to be applied, as well as several instances where colour values need to be quoted to for proper interpolation:

```
Warning: You probably don't mean to use the color value black in interpolation here.
It may end up represented as black, which will likely produce invalid CSS.
Always quote color names when using them as strings or map keys (for example, "black").
If you really want to use the color value here, use '"" + $name'.

   ╷
77 │   .bg-#{$name} {
   │         ^^^^^
   ╵
    src/scss/elements/_colours.scss 77:9  @import
    src/scss/_styles.scss 15:9            @import
    src/scss/great-styles.scss 12:9       root stylesheet
```

2021-11-02 08:41 UTC, froddd commented on src/scss/elements/_grid.scss
> +    width: percentage(3 * 0.25);
Can we use `math.div(3, 4)` here to make it consistent with other widths -- this would help readability. Applies to all other instances below.

2021-11-02 08:41 UTC, bobmeredith submitted a review, later dismissed
LGTM

2021-11-02 17:39 UTC, froddd submitted a review, later dismissed
Small suggestion added.

I see the remaining `Using / for division is deprecated` warnings left when running `npm run storybook` are down to font-awesome. It seems a fix is in the works but hasn't been released yet: https://github.com/FortAwesome/Font-Awesome/issues/17946 -- maybe keep an eye on it.

2021-11-02 17:39 UTC, froddd commented on src/scss/elements/_colours.scss
> +  .bg-#{"" + $name} {
I'm going to be a pain: even though this fix works, given the list above is a dictionary of values/keys, I'd actually expect the keys to be treated as such and be strings rather than literals, to avoid having to cast them when defining selectors. So, the change I'd expect to see is in the `$colours` definition:

```scss
$colours:
  ($black, 'black'),
  ($grey, 'grey'),
  ($mid-grey, 'mid-grey'),
  // ...
```

2021-11-02 18:21 UTC, seijihg commented on src/scss/elements/_colours.scss
> +  .bg-#{"" + $name} {
haha ah ok lemme fix it abit more manual labour xD 

no worries u are not being pain haha

2021-11-03 07:58 UTC, froddd approved these changes
Looks good!

2021-11-03 07:59 UTC, merged